version: "3"

services:
  vc-postgres-db:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - vc-nest-postgres:/var/lib/postgresql/data
  vc-app-be:
    image: node:19
    restart: always
    working_dir: /app
    volumes:
      - ./vc-employee-maintenance-app-be:/app
      - /app/node_modules
    ports:
      - 4000:4000
    depends_on:
      - vc-postgres-db
    command: sh -c "npm install && npm run start:dev"
  vc-app-fe:
    image: node:19
    restart: always
    working_dir: /app
    volumes:
      - ./vc-employee-maintenance-app-fe:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - vc-postgres-db
      - vc-app-be
    command: sh -c "npm install && npm run dev"
volumes:
  vc-nest-postgres:
